steps:
  - key: build-docker
    label: ':docker: Build Docker Image'
    command:
      - docker build -f ../Dockerfile -t hello-app . # Reference Dockerfile relative to the .buildkite directory
      - docker save hello-app -o hello-app.tar # Save the Docker image as a .tar file
    artifact_paths:
      - 'hello-app.tar' # Upload the Docker image as an artifact
